namespace FireLord
{
    public enum BoneIndex
    {
        Pelvis,
        L_Thigh,
        L_Calf,
        L_Foot,
        L_Toe0,
        R_Thigh,
        R_Calf,
        R_Foot,
        R_Toe0,
        Spine,
        Spine1,
        Spine2,
        Neck,
        Head,
        L_Clavicle,
        L_UpperArm_Twist,
        L_UpperArm_Twist1,
        L_ForeTwist,
        L_ForeTwist1,
        L_Hand,
        L_Finger0,
        R_Clavicle,
        R_UpperArm_Twist,
        R_UpperArm_Twist1,
        R_ForeTwist,
        R_ForeTwist1,
        R_Hand,
        R_Finger0,
    }
}
